default: &default
  adapter: postgresql
  encoding: unicode
  # pool: 5
  # kindly replace your database user access
  # username: postgres
  # kindly replace your database password
  # password: Temitope2604

development:
  <<: *default
  database: vecs_school_backend_development

test:
  <<: *default
  database: vecs_school_backend_test